# Generated by Django 2.0.6 on 2020-02-23 17:16

from django.db import migrations, models
import django.db.models.deletion
import foodlog.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200222_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='box',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('index_in_pic', models.IntegerField()),
                ('left', models.FloatField()),
                ('upper', models.FloatField()),
                ('right', models.FloatField()),
                ('down', models.FloatField()),
                ('prob', models.FloatField()),
                ('food_class', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='day_record',
            fields=[
                ('day_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='food_pic',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.FileField(storage=foodlog.storage.ImageStorage(), upload_to='food/')),
                ('upload_time', models.DateTimeField()),
                ('day_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodlog.day_record')),
            ],
        ),
        migrations.CreateModel(
            name='health_element',
            fields=[
                ('he_id', models.AutoField(primary_key=True, serialize=False)),
                ('Carbohydrates', models.FloatField(default=0)),
                ('Proteins', models.FloatField(default=0)),
                ('Fats', models.FloatField(default=0)),
                ('Minerals', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='food_pic',
            name='he_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodlog.health_element'),
        ),
        migrations.AddField(
            model_name='food_pic',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_info'),
        ),
        migrations.AddField(
            model_name='day_record',
            name='he_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodlog.health_element'),
        ),
        migrations.AddField(
            model_name='day_record',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_info'),
        ),
        migrations.AddField(
            model_name='box',
            name='he_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodlog.health_element'),
        ),
        migrations.AddField(
            model_name='box',
            name='pic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodlog.food_pic'),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together={('pic_id', 'index_in_pic')},
        ),
    ]
