# Generated by Django 2.0.6 on 2020-02-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_info',
        ),
    ]
