# Generated by Django 2.0.6 on 2020-02-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200222_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='user_info',
            name='height',
            field=models.FloatField(default=170),
        ),
        migrations.AddField(
            model_name='user_info',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('secret', 'secret')], default='secret', max_length=6),
        ),
        migrations.AddField(
            model_name='user_info',
            name='wight',
            field=models.FloatField(default=160),
        ),
    ]
